#encoding: utf-8

class SNPdist
	require 'rinruby'

	# Input 0: Array of homozygous SNP positions
	# Input 1: Array of heterozygous SNP positions
	# Input 2: Divides to get the frequency ratio for each break (fratio), div = no. of breaks
	# Input 3: The length of the genome
	# Output 1: List of frequencies: the ratios of homozygous to heterozygous SNPs at defined intervals (breaks)
	# Output 2: List of the breaks/intervals generated by div
	def self.fratio(hm, ht, div, genome_length) # Gets the frequency of SNPs at breaks of div length for the homozygous and heterozygous SNP arrays
		myr = RinRuby.new(echo = false)
		myr.assign 'hm', hm
		myr.assign 'ht', ht
		myr.assign 'div', div
		myr.assign 'l', genome_length
		myr.eval 'breaks <- c(0)
		for(i in 1:div){
		  breaks <- c(breaks,(l/div)*i)
		}
		hmc <- hist(hm, breaks=breaks, plot=FALSE)$counts
		htc <- hist(ht, breaks=breaks, plot=FALSE)$counts
		'
		breaks = myr.pull 'breaks'
		hmc = myr.pull 'hmc'
		htc = myr.pull 'htc'
		myr.quit
		x = 0
		fratio = []
		hmc.length.times do
			count = (((hmc[x] + 1).to_f / (htc[x] + 1).to_f)*10).to_i # a measure of frequency
			if count == 0
				fratio << 0
			else
				fratio << count - 1
			end
			x+=1
		end
		return fratio, breaks
	end

	# Input 0: The output of fratio method
	# Input 1: div = number of breaks
	# Input 2: The length of the genome
	# Output: A list of "hypothetical" SNP positions which represents the distribution of homozygous/heterozygous SNP density ratio
	def self.hyp_snps(fratio_breaks, div, genome_length)
		hyp = []
		x = 0
		fratio_breaks[0].each do |freq| 
			freq.times do
				hyp << rand(genome_length/div.to_f) + fratio_breaks[1][x] # random value from within the range that the freq has been taken
			end
			x+=1
		end
		return hyp # These don't need to be unique or integers like the real SNPs, since they are just representing a distribution
	end

	# Input 0: A list of "hypothetical" SNP positions which represents the distribution of homozygous/heterozygous SNP density ratio
	# Input 1: Location at which to save the plot
	# Input 2: The dataset to use (and the sub-folder to save the plot in)
	# Input 3: The generation of the genetic algorithm the ratio is being plotted for
	# Input 4: The length of the genome
	# Output: plot of the hypothetical SNP density, representing the distribution of homozygous/heterozygous SNP density ratio across the genome
	def self.plot_hyp(hyp, location, dataset_run, gen, genome_length)
		myr = RinRuby.new(echo = false)
		myr.assign 'hyp', hyp
		myr.assign 'location', location
		myr.assign 'dataset_run', dataset_run
		myr.assign 'gen', gen
		myr.assign 'genome_length', genome_length
		myr.eval 'png(paste("~/",location,"/", dataset_run,"/gen_", gen, "_best_permutation_distribution.png", sep=""))
		plot((1:512)*(genome_length/512), density(hyp)$y, xlab="Genome", ylab="Approximated ratio of homozygous to heterozygous SNP density")
		dev.off()'		
		myr.quit
	end

	def self.plot_hyp2(hyp, location, dataset_run, gen, genome_length, name)
		myr = RinRuby.new(echo = false)
		myr.assign 'hyp', hyp
		myr.assign 'location', location
		myr.assign 'dataset_run', dataset_run
		myr.assign 'gen', gen
		myr.assign 'genome_length', genome_length
		myr.assign 'name', name
		myr.eval 'png(paste("~/",location,"/", dataset_run,"/gen_", gen, "/", name, ".png", sep=""))
		plot((1:512)*(genome_length/512), density(hyp)$y, xlab="Genome", ylab="Approximated ratio of homozygous to heterozygous SNP density")
		dev.off()'		
		myr.quit
	end
	# Input 0: List of homozygous SNP positions
	# Input 1: List of heterozygous SNP positions
	# Input 2: Location at which to save the plot
	# Input 3: The dataset to use (and the sub-folder to save the plot in)
	# Input 4: The length of the genome
	# Input 5: Name of plot
	# Ootput: Plot of ratio of hom/het SNP density
	def self.plot_dens(hm, ht, location, dataset, genome_length, name)
		myr = RinRuby.new(echo = false)
		myr.assign 'hm', hm
		myr.assign 'ht', ht
		myr.assign 'location', location
		myr.assign 'dataset', dataset
		myr.assign 'genome_length', genome_length
		myr.assign 'name', name
		myr.eval 'hmd <- density(hm, from=0, to=genome_length)
		htd <- density(ht, from=0, to=genome_length)
		ratio <- hmd$y/htd$y'
		myr.eval 'png(paste("~/",location,"/", dataset,"/", name, ".png", sep=""))
		plot((1:512)*(genome_length/512), ratio, xlab="Genome", ylab="Ratio of homozygous to heterozygous SNP density")
		dev.off()'
		myr.quit
	end

	# Input 0: The theoretical distribution we want to test permutations against: A list of "hypothetical" SNP positions
	# Input 1: The distribution of hypothetical SNPs derived from the permutation of contigs we want to assess the fitness of
	# Output: Q-Q plot pearsons correlation: 0 > value <= 1 that tells you how similar the distributions of example_ratio and ratio are
	def self.qq_cor(example_ratio, ratio)
		myr = RinRuby.new(echo = false)
		myr.assign 'ex', example_ratio
		myr.assign 'ra', ratio
		myr.eval 'qqp <- qqplot(ex, ra, plot.it=FALSE)
		corr <- cor(qqp$x,qqp$y)'
		corr = myr.pull 'corr'
		myr.quit
		return corr
	end
end